### ISSUE TITLE
Curse allowing download of version 1.11 mod from 1.11.2 install

### ISSUE THREAD

**Issue by kragnoth** [TakeTenGaming/DatMod#48]
Please either update the version checker in the compiled jar, or remove the version checking in the compiled jar completely before next 1.11.2 release.  Or release a buildscript so that up to date versions can be compiled by end user.

Thanks

**Comment by xlxAciDxlx** [comment]
Can you explain the problem a bit better? I'm afraid I'm not understanding the issue. Also, the Version Checker will see an overhaul in the next release of both DatMod and TenCore, though that's mostly to put it inline with Forge's internal version checker.

**Comment by kragnoth** [comment]
The 1.11 version is showing up in 1.11.2.  When you run the 1.11 version in 1.11.2, it says "DatMod requires version 1.11" and stops minecraft from loading.

**Comment by xlxAciDxlx** [comment]
Ahh okay, that's my bad. For now I'll change the specification on CurseForge for what versions it works under. Thanks for the heads up!

**Comment by xlxAciDxlx** [comment]
This *should* be fixed for v2.0.0 once it's released, but obviously I'm only one person coding, testing and managing - so it may need to be tweaked once it hits the public. That release should be coming sometime in the next few days.

**Comment by xlxAciDxlx** [comment]
This should be fixed now. :)
